import Link from "next/link";
import { Plus } from "lucide-react";
import { db } from "@/lib/db";
import { formatMoney } from "@/lib/format";

export default async function AdminProductsPage() {
  const products = await db.product.findMany({ include: { category: true, variants: { include: { inventory: true }, orderBy: { price: "asc" } } }, orderBy: { updatedAt: "desc" } });
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Catalog</p><h1 className="display-title mt-1 text-5xl">Products</h1></div><Link className="button-primary" href="/admin/products/new"><Plus size={17} /> Add product</Link></div><div className="surface mt-8 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-black/10 bg-[#e8e3da]/60 text-xs uppercase tracking-wide text-[#6e675e]"><tr><th className="px-5 py-3">Product</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Variants</th><th className="px-5 py-3">Available stock</th><th className="px-5 py-3">From</th></tr></thead><tbody>{products.map((product) => { const available = product.variants.reduce((total, variant) => total + Math.max((variant.inventory?.onHand ?? 0) - (variant.inventory?.reserved ?? 0), 0), 0); const price = product.variants[0]?.price; return <tr className="border-b border-black/10 last:border-0" key={product.id}><td className="px-5 py-4"><Link className="font-bold hover:text-[#cb5a2e]" href={`/admin/products/${product.id}`}>{product.name}</Link><p className="mt-1 text-xs text-[#6e675e]">{product.sku}</p></td><td className="px-5 py-4">{product.category.name}</td><td className="px-5 py-4"><span className="bg-[#e8e3da] px-2 py-1 text-[10px] font-bold tracking-wide">{product.status}</span></td><td className="px-5 py-4">{product.variants.length}</td><td className="px-5 py-4">{available}</td><td className="px-5 py-4 font-bold">{price ? formatMoney(price) : "—"}</td></tr>; })}</tbody></table>{!products.length && <p className="p-6 text-sm text-[#6e675e]">Create the first product to begin selling.</p>}</div></div>;
}
