"use client";

import { useActionState } from "react";
import { saveCouponAction, type AdminActionState } from "@/app/actions/admin";

type CouponFormProps = {
  coupon?: { id: string; code: string; type: "PERCENTAGE" | "FIXED"; value: number; minimumOrder: number | null; maximumDiscount: number | null; startsAt: string; expiresAt: string; usageLimit: number | null; perUserLimit: number | null; isActive: boolean; productIds: string[]; categoryIds: string[] };
};

export function CouponForm({ coupon }: CouponFormProps) {
  const [state, action, pending] = useActionState<AdminActionState, FormData>(saveCouponAction, undefined);
  return <form action={action} className="grid gap-3 border border-black/10 p-4"><input name="id" type="hidden" value={coupon?.id ?? ""} /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold">Code<input className="input-field mt-1 uppercase" defaultValue={coupon?.code} name="code" required /></label><label className="text-xs font-bold">Type<select className="input-field mt-1" defaultValue={coupon?.type ?? "PERCENTAGE"} name="type"><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed (paisa)</option></select></label><label className="text-xs font-bold">Value<input className="input-field mt-1" defaultValue={coupon?.value ?? ""} min="1" name="value" required type="number" /></label><label className="text-xs font-bold">Minimum order (paisa)<input className="input-field mt-1" defaultValue={coupon?.minimumOrder ?? ""} min="0" name="minimumOrder" type="number" /></label><label className="text-xs font-bold">Maximum discount (paisa)<input className="input-field mt-1" defaultValue={coupon?.maximumDiscount ?? ""} min="1" name="maximumDiscount" type="number" /></label><label className="text-xs font-bold">Start date<input className="input-field mt-1" defaultValue={coupon?.startsAt} name="startsAt" type="date" /></label><label className="text-xs font-bold">Expiry date<input className="input-field mt-1" defaultValue={coupon?.expiresAt} name="expiresAt" type="date" /></label><label className="text-xs font-bold">Total use limit<input className="input-field mt-1" defaultValue={coupon?.usageLimit ?? ""} min="1" name="usageLimit" type="number" /></label><label className="text-xs font-bold">Per-customer limit<input className="input-field mt-1" defaultValue={coupon?.perUserLimit ?? ""} min="1" name="perUserLimit" type="number" /></label><label className="flex items-end gap-2 pb-3 text-xs font-bold"><input defaultChecked={coupon?.isActive ?? true} name="isActive" type="checkbox" /> Active</label></div><label className="text-xs font-bold">Product IDs <span className="font-normal text-[#6e675e]">(comma-separated, optional)</span><textarea className="input-field mt-1 min-h-16" defaultValue={coupon?.productIds.join(", ") ?? ""} name="productIds" /></label><label className="text-xs font-bold">Category IDs <span className="font-normal text-[#6e675e]">(comma-separated, optional)</span><textarea className="input-field mt-1 min-h-16" defaultValue={coupon?.categoryIds.join(", ") ?? ""} name="categoryIds" /></label><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-[#6e675e]">Scopes are optional. Leave both blank to apply store-wide.</p><button className="button-primary px-4 py-2" disabled={pending} type="submit">{pending ? "Saving…" : coupon ? "Save coupon" : "Create coupon"}</button></div>{state?.error && <p className="text-sm text-red-700">{state.error}</p>}{state?.success && <p className="text-sm text-emerald-700">{state.success}</p>}</form>;
}
