"use client";

import { useActionState } from "react";
import { saveSettingsAction, type AdminActionState } from "@/app/actions/admin";

type SettingsFormProps = {
  settings?: { storeName: string; contactEmail: string | null; contactPhone: string | null; logoUrl: string | null; defaultMetaTitle: string | null; defaultMetaDescription: string | null; aiProvider: string | null; aiModel: string | null; aiSystemPrompt: string | null; socialLinks: string[] };
};

export function SettingsForm({ settings }: SettingsFormProps) {
  const [state, action, pending] = useActionState<AdminActionState, FormData>(saveSettingsAction, undefined);
  return <form action={action} className="surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Store configuration</p><h1 className="display-title mt-1 text-4xl">Settings</h1></div><button className="button-primary" disabled={pending} type="submit">{pending ? "Saving…" : "Save settings"}</button></div>{state?.error && <p className="mt-4 text-sm text-red-700">{state.error}</p>}{state?.success && <p className="mt-4 text-sm text-emerald-700">{state.success}</p>}<div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Store name<input className="input-field mt-2" defaultValue={settings?.storeName ?? "SEVEN ROCK"} name="storeName" required /></label><label className="text-sm font-bold">Contact email<input className="input-field mt-2" defaultValue={settings?.contactEmail ?? ""} name="contactEmail" type="email" /></label><label className="text-sm font-bold">Contact phone<input className="input-field mt-2" defaultValue={settings?.contactPhone ?? ""} name="contactPhone" /></label><label className="text-sm font-bold">Logo URL<input className="input-field mt-2" defaultValue={settings?.logoUrl ?? ""} name="logoUrl" type="url" /></label><label className="text-sm font-bold">Default SEO title<input className="input-field mt-2" defaultValue={settings?.defaultMetaTitle ?? ""} maxLength={70} name="defaultMetaTitle" /></label><label className="text-sm font-bold">Default SEO description<textarea className="input-field mt-2 min-h-20" defaultValue={settings?.defaultMetaDescription ?? ""} maxLength={160} name="defaultMetaDescription" /></label><label className="text-sm font-bold">AI provider<input className="input-field mt-2" defaultValue={settings?.aiProvider ?? ""} name="aiProvider" placeholder="Configured provider name" /></label><label className="text-sm font-bold">AI model<input className="input-field mt-2" defaultValue={settings?.aiModel ?? ""} name="aiModel" placeholder="Configured model identifier" /></label><label className="text-sm font-bold md:col-span-2">AI system prompt<textarea className="input-field mt-2 min-h-36" defaultValue={settings?.aiSystemPrompt ?? ""} maxLength={4000} name="aiSystemPrompt" /></label><label className="text-sm font-bold md:col-span-2">Social URLs <span className="font-normal text-[#6e675e]">(one per line)</span><textarea className="input-field mt-2 min-h-24" defaultValue={settings?.socialLinks.join("\n") ?? ""} name="socialLinks" /></label></div></form>;
}
