import Link from "next/link";
import { InventoryAdjustmentForm } from "@/components/admin/inventory-adjustment-form";
import { db } from "@/lib/db";
import { formatDate } from "@/lib/format";

export default async function AdminInventoryPage() {
  const inventory = await db.inventoryItem.findMany({
    include: { variant: { include: { product: { select: { id: true, name: true } } } }, adjustments: { include: { createdBy: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 3 } },
    orderBy: { updatedAt: "desc" },
  });
  return <div><div><p className="eyebrow">Stock control</p><h1 className="display-title mt-1 text-5xl">Inventory</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#6e675e]">Adjustments are recorded against a permanent inventory ledger and cannot reduce stock below quantities reserved for active orders.</p></div><div className="mt-8 space-y-4">{inventory.map((item) => { const available = item.onHand - item.reserved; const lowStock = available <= item.reorderLevel; return <article className="surface p-5" key={item.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><Link className="font-bold hover:text-[#cb5a2e]" href={`/admin/products/${item.variant.product.id}`}>{item.variant.product.name}</Link><p className="mt-1 text-xs text-[#6e675e]">{item.variant.sku}{item.variant.color ? ` · ${item.variant.color}` : ""}{item.variant.size ? ` · ${item.variant.size}` : ""}</p></div><div className="flex gap-2 text-right"><div className="border border-black/10 px-3 py-2"><p className="text-[10px] font-bold uppercase tracking-wide text-[#6e675e]">Available</p><p className={lowStock ? "mt-1 font-bold text-[#cb5a2e]" : "mt-1 font-bold"}>{available}</p></div><div className="border border-black/10 px-3 py-2"><p className="text-[10px] font-bold uppercase tracking-wide text-[#6e675e]">Reserved</p><p className="mt-1 font-bold">{item.reserved}</p></div><div className="border border-black/10 px-3 py-2"><p className="text-[10px] font-bold uppercase tracking-wide text-[#6e675e]">On hand</p><p className="mt-1 font-bold">{item.onHand}</p></div></div></div><InventoryAdjustmentForm inventoryItemId={item.id} />{item.adjustments.length > 0 && <div className="mt-4 border-t border-black/10 pt-3"><p className="text-xs font-bold uppercase tracking-wide text-[#6e675e]">Recent ledger entries</p><ul className="mt-2 space-y-1 text-xs text-[#6e675e]">{item.adjustments.map((adjustment) => <li key={adjustment.id}>{formatDate(adjustment.createdAt)} · <strong className="text-[#171512]">{adjustment.quantityDelta > 0 ? "+" : ""}{adjustment.quantityDelta}</strong> · {adjustment.reason.replaceAll("_", " ")}{adjustment.createdBy ? ` by ${adjustment.createdBy.name}` : ""}{adjustment.note ? ` — ${adjustment.note}` : ""}</li>)}</ul></div>}</article>; })}</div>{!inventory.length && <div className="surface mt-8 p-6 text-sm text-[#6e675e]">Inventory will appear after products with variants are created.</div>}</div>;
}
